version: "3"

services:
  project-data:
    image: docker.io/bitnami/postgresql:14
    container_name: project-data
    ports:
      - "5432:5432"
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - project-data:/bitnami/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=theuser
      - POSTGRES_PASSWORD=raTJGNaSDKRQO131951sja

volumes:
  project-data: